#!/usr/bin/env node

'use strict' 

var c = require("skilstak-colors");


var printPlain = function (message) {
  console.log(c.clear + c.rc() + message  + c.x);
}

var printColor = function (message) {
  while (true) {
    console.log(c.clear + c.rc() + message + c.x);
  }
}

var printNyan = function (message) {
  while (true) {
  console.log(c.rc() + message + c.x);
  } 
}
var printMulti = function (message) {
  console.log(c.multi(message));

    }    

printNyan("Biscuits");

