#!/usr/bin/env node

'use strict'


var c = require("skilstak-colors");


var printPlain = function (message) {
  console.log(c.clear + c.rc() + message  + c.x);
}

var printColor = function (message) {
  while (true) {
    console.log(c.clear + c.rc() + message + c.x);
  }
}

var printNyan = function (message) {
  while (true) {
  console.log(c.rc() + message + c.x);
  } 
}

var printMulti = function (message) {
  console.log(c.multi(message));


    }


var name = "World";

var option = "-m";

var firstValue = process.argv[2];
if (firstValue[0] === "-") {
  option = firstValue;
  console.log("I have a switch: " + option);
}

if (option === "-m") {
  printMulti(name);
}

